name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        github_access_token: ${{ secrets.PORTFILIO_CI_CD_TOKEN }}
        build_configuration: staging # The build environment for the app. please look configurations in your angular.json
        base_href: /portfolio/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: dist/portfolio # The folder where your project is supposed to be after running ng build by the action.
